### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by CzEMC** [Cnly/WowSuchCleaner#1]
Your maven pom.xml doesn't have met dependency's. Adding the BusyInv and Crafter to the project still returns errors. How is your IDE setup?

**Comment by Cnly** [comment]
Hi, perhaps you could provide some details on the errors returned? pom.xml works fine both on my machine and the CI.

**Comment by CzEMC** [comment]
There's no errors, it's just that the pom.xml doesn't include the repo's that BusyInv and Crafter are. Is this intentional, as we have to setup the environment to include those libraries locally?

**Comment by Cnly** [comment]
Yes, you need to `mvn install` those two dependencies locally. Here's how you can get them quickly:

```
git clone https://github.com/Cnly/Crafter.git
git clone https://github.com/Cnly/BusyInv.git
```

Then you can `cd` into their directories and run `mvn clean install`.

**Comment by CzEMC** [comment]
Ah. Thank you! It finally compiles and packages!

**Comment by Cnly** [comment]
Okay, I'm sorry it bothered you. I will add that to README.md. Thank you for your report, and, if things are working well now, please close this issue. :)
