### ISSUE TITLE
Codacy/PR Quality Review on develop

### ISSUE THREAD

**Issue by CzEMC** [Cnly/WowSuchCleaner#3]
When trying to pull request on the branch "develop" the Codacy/PR Quality Review fails it because it is not selected to be analysed. Shall contributes request to make merges on the master branch?

Error: `Codacy/PR Quality Review — Codacy was unable to analyse your pull request.`

**Comment by Cnly** [comment]
No, please make PRs on `develop`. This problem is fixed now.
